# FROM php:8.0.24-fpm-alpine3.16
FROM php:7.4-fpm-alpine

WORKDIR /var/www/html
COPY . .

RUN apk --update add wget \ 
                    --virtual .build-deps $PHPIZE_DEPS \
                    curl \
                    git 

RUN docker-php-ext-install \
                mysqli \
                pdo_mysql \
                intl
                # bz2 \
                # zlib \
                # gd \ 
                # pdo \
                # mbstring \
                # pdo_mysql \

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer 
# RUN composer update

CMD ["/bin/sh", "-c"]