version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-apache.dev
    # command: sh -c "composer install && php serve"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      