FROM php:apache-bullseye
RUN apt update 
RUN apt install -y libicu-dev \
  libzip-dev \
  git \
  zip \
  unzip
# RUN rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install intl zip

# COPY apache2/default.conf /etc/apache2/
# COPY apache/default.conf .
WORKDIR /var/www/html/

RUN a2enmod rewrite

COPY . .

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

EXPOSE 80

# CMD ["composer", "install" ]
# ENTRYPOINT ["bash", "./Docker.sh"]
# CMD [ "/bin/sh", "-c" ]
# CMD [ "tail", "-100 ", "/var/log/apache2/access.log" ]